call plug#begin()
Plug 'preservim/NERDTree'
Plug 'kyazdani42/nvim-web-devicons'  
Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}
Plug 'mattn/emmet-vim'
Plug 'itchyny/lightline.vim'
Plug 'chriskempson/base16-vim'
Plug 'akinsho/bufferline.nvim', { 'tag': 'v2.*' }
Plug 'jiangmiao/auto-pairs'
Plug 'tpope/vim-fugitive'
Plug 'mhinz/vim-startify'
Plug 'kdheepak/lazygit.nvim'
Plug 'ap/vim-css-color'
Plug 'daviesjamie/vim-base16-lightline'
Plug 'easymotion/vim-easymotion'
Plug 'terryma/vim-multiple-cursors'
Plug 'junegunn/fzf'
Plug 'airblade/vim-rooter'
call plug#end()


set termguicolors
colorscheme base16-default-dark

nnoremap <SPACE> <Nop>
map <Space> <Leader>


"fuzzy finder
set rtp+=/usr/local/opt/fzf
nnoremap <leader>f :FZF <CR>

"copy paste from clipboard bindings
noremap <Leader>y "*y
noremap <Leader>p "*p
noremap <Leader>Y "+y
noremap <Leader>P "+p

"minimap
let g:minimap_width = 10
let g:minimap_auto_start = 1
let g:minimap_auto_start_win_enter = 1

" Lightline
let g:lightline = {
      \ 'colorscheme': 'base16', 
      \ }
set laststatus=2
" LazyGit
nnoremap <silent> <leader>gl :LazyGit<CR>

"Telescope	
"nnoremap <leader>ff <cmd>Telescope find_files<cr>
"nnoremap <leader>fg <cmd>Telescope live_grep<cr>
"nnoremap <leader>fb <cmd>Telescope buffers<cr>
"nnoremap <leader>fh <cmd>Telescope oldfiles<cr>
"nnoremap <leader>fe <cmd> Telescope file_browser<cr> 


"bufferline

lua << EOF
require('bufferline').setup {
		separator_style = "paddedslant" 
}
EOF

"easymotion
" Move to char

nnoremap S <Nop>
map S <Plug>(easymotion-bd-f)
nmap S <Plug>(easymotion-overwin-f)

" Move to word
nnoremap s <Nop>
map  s <Plug>(easymotion-bd-w)
nmap s <Plug>(easymotion-overwin-w)

" Move to line
map <leader>L <Plug>(easymotion-bd-jk)
nmap <leader>L <Plug>(easymotion-overwin-line)


"
"dashboard
"

" Nerd tree settings n shit
nmap <LEADER>nto :NERDTreeToggle<CR>
nmap <LEADER>ntf :NERDTreeFocus<CR>
nmap <LEADER>ntt :NERDTreeFind<CR>
let g:NERDTreeDirArrowExpandable = '|'
let g:NERDTreeDirArrowCollapsible = '~'
let nerdtreeshowlinenumbers=1
autocmd FileType nerdtree setlocal relativenumber


" coc

function! s:check_back_space() abort
let col = col('.') - 1
return !col || getline('.')[col - 1]  =~ '\s'
endfunction

inoremap <silent><expr> <TAB>
	  \ pumvisible() ? "\<C-n>" :
	  \ <SID>check_back_space() ? "\<TAB>" :
	  \ coc#refresh()


inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<CR>"

"vim
nmap <LEADER>tn :tabnew<CR>
nnoremap <LEADER>j <C-W><C-J>
nnoremap <LEADER>k <C-W><C-K>
nnoremap <LEADER>l <C-W><C-L>
nnoremap <LEADER>h <C-W><C-H>
set mouse=a
set scrolloff=8
set number relativenumber
set nu rnu
set showtabline=2
let $NVIM_TUI_ENABLE_TRUE_COLOR=1
set autochdir
syntax on
